### ISSUE TITLE
creating bitcoin address

### ISSUE THREAD

**Issue by justaskan** [getamis/alice#102]
Since none of the participants have access to the private key, is it possible to create a bitcoin wallet address that requires knowing the private key?

**Comment by cychuang0924** [comment]
After DKG, then you can get a public key in common of all participants. This public key can be used to obtain the associated bitcoin wallet address.

**Comment by aboozaid** [comment]
@cychuang0924 can we create a solana address after generating dkg result? if yes could you please provide some guidance to follow to generate it?

**Comment by cychuang0924** [comment]
@aboozaid Hi, [aboozaid](https://github.com/aboozaid),

     *Currently, the DKG result does not support computing a SOL address.*

Here’s an overview of how a SOL address is computed:

   1. Use Alice's internal method CompressedPoint(secret, true)
   <https://github.com/getamis/alice/blob/7bfdde65a352c320aea86cd883dcfeebf00796ea/crypto/elliptic/ed25519.go#L60>
   to generate the correct public key format.
   2. Apply Base58 encoding to the public key generated above to obtain the
   SOL address.

The issue lies in the fact that none of the known MPC ECDSA libraries
support step 1 in compliance with RFC8032
<https://datatracker.ietf.org/doc/html/rfc8032> for public key generation.
As a result, the SOL address derived using Alice's output will be
incorrect. According to RFC8032, private keys must be generated in a
specific way: using SHA-512 to hash a seed and taking the first 32 bytes as
the private key.

Regarding whether Alice can meet this requirement, the answer is *yes*, but
implementing this feature in the short term is not feasible. We offer the
following two suggestions (both require replacing the DKG component, while
Sign and Refresh functionalities can continue to work):
Method 1:

This method can perfectly support the 2-2 scenario, but it is not
straightforward. It requires implementing SHA-512 in MPC. You can refer to
our 2-party BIP32
<https://github.com/getamis/alice/tree/master/crypto/bip32> implementation
and use our library for such MPC computations.
Method 2:

A more direct solution is as follows:

   1. Generate a secret.
   2. Use CompressedPoint(secret, true) and Base58 to generate the SOL
   address.
   3. Compute sha512(secret)[0:32] to derive the private key. Then, use
   Shamir Secret Sharing or our provided HSS splitting method to divide this
   private key into the required number of shares.

This process ensures that, apart from the initial generation where the
private key is exposed, subsequent usage involves managing the private key
through shares, enhancing security. Additionally, during signing, Alice can
still be used to generate signatures, maintaining consistency with the
original management approach.

If you have any problem, please let me know. Thanks!

Sincerely,

Chih Yun

**Comment by aboozaid** [comment]
> @aboozaid Hi, [aboozaid](https://github.com/aboozaid), *Currently, the DKG result does not support computing a SOL address.* Here’s an overview of how a SOL address is computed: 1. Use Alice's internal method CompressedPoint(secret, true) <https://github.com/getamis/alice/blob/7bfdde65a352c320aea86cd883dcfeebf00796ea/crypto/elliptic/ed25519.go#L60> to generate the correct public key format. 2. Apply Base58 encoding to the public key generated above to obtain the SOL address. The issue lies in the fact that none of the known MPC ECDSA libraries support step 1 in compliance with RFC8032 <https://datatracker.ietf.org/doc/html/rfc8032> for public key generation. As a result, the SOL address derived using Alice's output will be incorrect. According to RFC8032, private keys must be generated in a specific way: using SHA-512 to hash a seed and taking the first 32 bytes as the private key. Regarding whether Alice can meet this requirement, the answer is *yes*, but implementing this feature in the short term is not feasible. We offer the following two suggestions (both require replacing the DKG component, while Sign and Refresh functionalities can continue to work): Method 1: This method can perfectly support the 2-2 scenario, but it is not straightforward. It requires implementing SHA-512 in MPC. You can refer to our 2-party BIP32 <https://github.com/getamis/alice/tree/master/crypto/bip32> implementation and use our library for such MPC computations. Method 2: A more direct solution is as follows: 1. Generate a secret. 2. Use CompressedPoint(secret, true) and Base58 to generate the SOL address. 3. Compute sha512(secret)[0:32] to derive the private key. Then, use Shamir Secret Sharing or our provided HSS splitting method to divide this private key into the required number of shares. This process ensures that, apart from the initial generation where the private key is exposed, subsequent usage involves managing the private key through shares, enhancing security. Additionally, during signing, Alice can still be used to generate signatures, maintaining consistency with the original management approach. If you have any problem, please let me know. Thanks! Sincerely, Chih Yun

Thank you @cychuang0924 for the detailed answer and your time to reply really appreciated :)

I will take some time to get into 2-party BIP32 solution you mentioned before deciding which approach I will take but I want to ask Is that goes the same with any EdDSA based blockchain like Algorand & Stellar?

**Comment by cychuang0924** [comment]
Hi Assem,

A rough study of Stellar and Algorand reveals that their EdDSA
implementations both follow the RFC 8032 specification. Therefore, they
face the same issue as SOL that needs to be addressed.

Sincerely,

Chih Yun

Assem ***@***.***> 於 2025年1月15日 週三 下午3:18寫道：
